"""added mst_course table

Revision ID: 381eec4b141c
Revises: dab30543de03
Create Date: 2025-04-16 16:41:53.641964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381eec4b141c'
down_revision: Union[str, None] = 'dab30543de03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mst_students', sa.Column('stud_photo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mst_students', 'stud_photo')
    # ### end Alembic commands ###
